package com.example.sciencequiz

// Datenklasse
data class SciencQuizEntry(
    var discipline: List<String>,
    val person: List<String>,
    val discovery: List<String>
)

object ScienceQuizyData {
    val ScienceQuist = listOf(
// --- MATHEMATIK ---
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Carl Friedrich Gauß"), discovery = listOf("Die Glockenkurve (Normalverteilung) und der Fundamentalsatz der Algebra")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Leonhard Euler"), discovery = listOf("Die Basis des natürlichen Logarithmus (e) und die Formel e^(i*pi) + 1 = 0")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Alan Turing"), discovery = listOf("Konzept eines universellen Computers und die Grundlagen der künstlichen Intelligenz")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Ada Lovelace"), discovery = listOf("Erstellung des ersten Programms für eine mechanische Rechenmaschine")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Pythagoras"), discovery = listOf("Die Formel a² + b² = c² für rechtwinklige Dreiecke")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Euclid"), discovery = listOf("Systematische Zusammenfassung der Geometrie und Beweis der Unendlichkeit der Primzahlen")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Emmy Noether"), discovery = listOf("Theorem über den tiefen Zusammenhang zwischen Symmetrien und Erhaltungssätzen")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Blaise Pascal"), discovery = listOf("Entwicklung der Wahrscheinlichkeitsrechnung und ein berühmtes Zahlendreieck")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Gottfried Wilhelm Leibniz"), discovery = listOf("Entwicklung der Infinitesimalrechnung und des binären Zahlensystems")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Bernhard Riemann"), discovery = listOf("Grundlagen der gekrümmten Geometrie, die später für die Relativitätstheorie wichtig wurden")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("John von Neumann"), discovery = listOf("Entwurf der modernen Computerarchitektur und Begründung der Spieltheorie")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Kurt Gödel"), discovery = listOf("Beweis, dass es in jedem Logiksystem unbeweisbare wahre Aussagen gibt")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Joseph Fourier"), discovery = listOf("Methode zur Zerlegung von Signalen in eine summe von Schwingungen")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Srinivasa Ramanujan"), discovery = listOf("Entdeckung hochkomplexer Identitäten in der Zahlentheorie ohne formale Ausbildung")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("David Hilbert"), discovery = listOf("Liste von 23 ungelösten Problemen, die die Mathematik des 20. Jahrhunderts prägten")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("René Descartes"), discovery = listOf("Verbindung von Algebra und Geometrie durch ein Koordinatensystem")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Pierre de Fermat"), discovery = listOf("Ein jahrhundertelang unbewiesener Satz über die Unlösbarkeit von a^n + b^n = c^n für n > 2")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Georg Cantor"), discovery = listOf("Begründung der Mengenlehre und Nachweis, dass es verschiedene Größen von Unendlichkeit gibt")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Katherine Johnson"), discovery = listOf("Berechnung der Flugbahnen für die Mercury- und Apollo-Missionen der NASA")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("George Boole"), discovery = listOf("Ein System der Logik, das nur auf 0 und 1 basiert")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("John Nash"), discovery = listOf("Konzept eines Gleichgewichtszustands in strategischen Spielen")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Grace Hopper"), discovery = listOf("Entwicklung des ersten Compilers und Pionierarbeit für moderne Programmiersprachen")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Andrew Wiles"), discovery = listOf("Beweis des letzten großen Satzes über die Unlösbarkeit von a^n + b^n = c^n für n > 2")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Bonaventura Cavalieri"), discovery = listOf("Prinzip zur Volumenberechnung von Körpern mittels paralleler Schnitte")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Augustin-Louis Cauchy"), discovery = listOf("Formulierung der mathematischen Strenge in der Analysis")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Évariste Galois"), discovery = listOf("Theorie zur Lösbarkeit algebraischer Gleichungen mittels Gruppen")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Henri Poincaré"), discovery = listOf("Begründung der algebraischen Topologie und Vorläufer der Chaosforschung")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Andrei Kolmogorow"), discovery = listOf("Axiomatische Begründung der modernen Wahrscheinlichkeitsrechnung")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Archimedes"), discovery = listOf("Näherungsverfahren für die Kreiszahl Pi und Hebelgesetz der Mechanik")),
        SciencQuizEntry(discipline = listOf("Mathematik"), person = listOf("Al-Chwarizmi"), discovery = listOf("Systematische Regeln zur Lösung linearer und quadratischer Gleichungen")),

// --- PHYSIK ---
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Albert Einstein"), discovery = listOf("Äquivalenz von Masse und Energie (E = mc²) sowie die Krümmung der Raumzeit")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Isaac Newton"), discovery = listOf("Gesetze der Bewegung und die universelle Gravitation")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Max Planck"), discovery = listOf("Entdeckung, dass Energie nur in winzigen, diskreten Paketen (Quanten) abgegeben wird")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Niels Bohr"), discovery = listOf("Entwurf eines Atommodells mit Elektronen auf stabilen Energiebahnen")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Werner Heisenberg"), discovery = listOf("Prinzip, dass Ort und Impuls eines Teilchens nicht gleichzeitig exakt bestimmt werden können")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Marie Curie"), discovery = listOf("Isolierung radioaktiver Elemente und Erforschung der Strahlung von Uran")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("James Clerk Maxwell"), discovery = listOf("Vereinigung von Elektrizität und Magnetismus zu einem gemeinsamen Feld")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Stephen Hawking"), discovery = listOf("Theoretische Vorhersage, dass Schwarze Löcher eine schwache Strahlung abgeben")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Erwin Schrödinger"), discovery = listOf("Zentrale Wellengleichung zur Beschreibung von Quantenzuständen")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Richard Feynman"), discovery = listOf("Anschauliche Diagramme zur Darstellung von Wechselwirkungen zwischen Elementarteilchen")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Michael Faraday"), discovery = listOf("Erzeugung von Strom durch Bewegung eines Magneten (Induktion)")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Galileo Galilei"), discovery = listOf("Nachweis, dass alle Körper im Vakuum gleich schnell fallen")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Ernest Rutherford"), discovery = listOf("Entdeckung, dass die Masse eines Atoms in einem winzigen Kern konzentriert ist")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Lise Meitner"), discovery = listOf("Theoretische Deutung der Spaltung von Atomkernen")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Nikola Tesla"), discovery = listOf("Entwicklung des Mehrphasen-Wechselstromsystems für die Stromversorgung")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Johannes Kepler"), discovery = listOf("Beschreibung der Planetenbewegungen auf elliptischen Bahnen")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Paul Dirac"), discovery = listOf("Vorhersage der Existenz von Antimaterie durch eine mathematische Gleichung")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Enrico Fermi"), discovery = listOf("Realisierung der ersten kontrollierten nuklearen Kettenreaktion")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Edwin Hubble"), discovery = listOf("Nachweis, dass sich das Universum ausdehnt und andere Galaxien existieren")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("J. J. Thomson"), discovery = listOf("Experimenteller Nachweis des Elektrons als Teil des Atoms")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Vera Rubin"), discovery = listOf("Nachweis der Existenz Dunkler Materie durch die Rotation von Galaxien")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Chien-Shiung Wu"), discovery = listOf("Experimenteller Beweis, dass die Natur nicht immer spiegelsymmetrisch ist (Paritätsverletzung)")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("James Watt"), discovery = listOf("Entscheidende Verbesserung der Dampfmaschine durch einen separaten Kondensator")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("John Bardeen"), discovery = listOf("Mit-Erfindung des Transistors und Entwicklung der Theorie der Supraleitung")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Wolfgang Pauli"), discovery = listOf("Ausschlussprinzip, nach dem zwei Elektronen nicht im selben Quantenzustand sein können")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Louis de Broglie"), discovery = listOf("Theorie des Welle-Teilchen-Dualismus für Materie (Materiewellen)")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Peter Higgs"), discovery = listOf("Postulat eines Feldes, das Elementarteilchen ihre Masse verleiht")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Thomas Young"), discovery = listOf("Doppelspaltexperiment zum Nachweis der Wellennatur des Lichts")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Heinrich Hertz"), discovery = listOf("Experimenteller Nachweis von elektromagnetischen Wellen")),
        SciencQuizEntry(discipline = listOf("Physik"), person = listOf("Wilhelm Conrad Röntgen"), discovery = listOf("Entdeckung einer neuen Art von unsichtbaren Strahlen")),

// --- CHEMIE ---
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Dmitri Mendelejew"), discovery = listOf("Anordnung der chemischen Elemente nach steigender Atommasse und Eigenschaften")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Antoine Lavoisier"), discovery = listOf("Erkenntnis, dass bei chemischen Reaktionen die Gesamtmasse erhalten bleibt")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Fritz Haber"), discovery = listOf("Industrielles Verfahren zur Bindung von Stickstoff aus der Luft zur Düngemittelherstellung")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Louis Pasteur"), discovery = listOf("Entdeckung, dass Erhitzung Lebensmittel haltbar macht und Keime abtötet")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Alfred Nobel"), discovery = listOf("Stabilisierung von Nitroglyzerin zu einem handhabbaren Sprengstoff")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("John Dalton"), discovery = listOf("Theorie, dass Materie aus unteilbaren Atomen unterschiedlicher Masse besteht")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("August Kekulé"), discovery = listOf("Entschlüsselung der kreisförmigen Struktur des Benzol-Moleküls")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Dorothy Hodgkin"), discovery = listOf("Bestimmung der komplexen Molekülstruktur von Penicillin und Vitamin B12")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Robert Bunsen"), discovery = listOf("Entwicklung der Spektralanalyse zur Identifizierung von Elementen anhand ihres Lichts")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Linus Pauling"), discovery = listOf("Erforschung der chemischen Bindung und der Struktur von Proteinen")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Svante Arrhenius"), discovery = listOf("Theorie, dass Säuren und Basen in Wasser in Ionen zerfallen")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Rosalind Franklin"), discovery = listOf("Erstellung der entscheidenden Röntgenbeugungsbilder der DNA-Struktur")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Glenn Seaborg"), discovery = listOf("Entdeckung und Synthese zahlreicher Elemente schwerer als Uran")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Mario Molina"), discovery = listOf("Warnung vor der Zerstörung der Ozonschicht durch künstliche Gase")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Stephanie Kwolek"), discovery = listOf("Erfindung einer extrem festen Kunstfaser für Schutzkleidung")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Irene Joliot-Curie"), discovery = listOf("Erzeugung künstlicher Radioaktivität durch die Bestrahlung stabiler Elemente")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Otto Hahn"), discovery = listOf("Entdeckung der Kernspaltung von schweren Atomkernen")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Robert Boyle"), discovery = listOf("Nachweis des umgekehrt proportionalen Verhältnisses von Druck und Volumen bei Gasen")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Amedeo Avogadro"), discovery = listOf("Hypothese, dass gleiche Gasvolumina die gleiche Teilchenzahl haben")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Friedrich Wöhler"), discovery = listOf("Künstliche Synthese von Harnstoff aus anorganischen Stoffen")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Humphry Davy"), discovery = listOf("Entdeckung von Natrium, Kalium und Calcium mittels Elektrolyse")),
        SciencQuizEntry(discipline = listOf("Chemie"), person = listOf("Justus von Liebig"), discovery = listOf("Erfindung des Mineraldüngers für die Landwirtschaft")),

// --- BIOLOGIE ---
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Charles Darwin"), discovery = listOf("Theorie der natürlichen Selektion als Antrieb der Artenentwicklung")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Gregor Mendel"), discovery = listOf("Entdeckung der Vererbungsregeln durch Kreuzung von Erbsenpflanzen")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Alexander Fleming"), discovery = listOf("Entdeckung der antibakteriellen Wirkung eines Schimmelpilzes")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("James Watson & Francis Crick"), discovery = listOf("Modellierung der Doppelhelix-Struktur der Erbsubstanz")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Robert Koch"), discovery = listOf("Identifizierung der Erreger von Milzbrand, Tuberkulose und Cholera")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Barbara McClintock"), discovery = listOf("Nachweis, dass Gene ihre Position auf den Chromosomen verändern können")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Rachel Carson"), discovery = listOf("Dokumentation der Gefahren von Pestizide für die Umwelt")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Lynn Margulis"), discovery = listOf("Theorie, dass komplexe Zellen aus der Verschmelzung einfacherer Organismen entstanden")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Karl Landsteiner"), discovery = listOf("Unterscheidung des menschlichen Blutes in verschiedene Gruppen")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Jennifer Doudna & Emmanuelle Charpentier"), discovery = listOf("Entwicklung einer präzisen Methode zur Bearbeitung des Genoms")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Kary Mullis"), discovery = listOf("Verfahren zur millionenfachen Vervielfältigung kleiner DNA-Proben")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Tu Youyou"), discovery = listOf("Gewinnung eines hocheffektiven Wirkstoffs gegen Malaria aus der Heilpflanzenkunde")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Jane Goodall"), discovery = listOf("Beobachtung des Werkzeuggebrauchs und Sozialverhaltens bei wilden Schimpansen")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("William Harvey"), discovery = listOf("Erste korrekte Beschreibung des großen Blutkreislaufs im Körper")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Antoni van Leeuwenhoek"), discovery = listOf("Erste detaillierte Beobachtungen von Bakterien und Einzellern mit selbst gebauten Mikroskopen")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Carl von Linné"), discovery = listOf("Entwicklung der binären Nomenklatur zur Klassifizierung von Pflanzen und Tieren")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Konrad Lorenz"), discovery = listOf("Erforschung des Verhaltens von Vögeln und das Prinzip der Prägung")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Paul Ehrlich"), discovery = listOf("Entwicklung der Seitenkettentheorie der Immunität und der ersten gezielten Chemotherapie")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Edward Jenner"), discovery = listOf("Entwicklung der allerersten Schutzimpfung durch die Nutzung von Kuhpockenviren")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Rudolf Virchow"), discovery = listOf("Formulierung des Grundsatzes, dass jede Zelle aus einer bereits existierenden Zelle entsteht")),
        SciencQuizEntry(discipline = listOf("Biologie"), person = listOf("Alexander von Humboldt"), discovery = listOf("Begründung der Biogeographie durch die Untersuchung von Pflanzenverteilungen in Höhenzonen")),

// --- INFORMATIK ---
        SciencQuizEntry(discipline = listOf("Informatik"), person = listOf("Tim Berners-Lee"), discovery = listOf("Erfindung des World Wide Web, von HTML und des ersten Webbrowsers")),
        SciencQuizEntry(discipline = listOf("Informatik"), person = listOf("Claude Shannon"), discovery = listOf("Begründung der Informationstheorie und Definition der kleinsten Informationseinheit (Bit)")),
        SciencQuizEntry(discipline = listOf("Informatik"), person = listOf("Dennis Ritchie"), discovery = listOf("Entwicklung der Programmiersprache C und Mitwirkung am Betriebssystem Unix")),
        SciencQuizEntry(discipline = listOf("Informatik"), person = listOf("Margaret Hamilton"), discovery = listOf("Entwicklung der robusten Bordsoftware für die erste Mondlandung")),
        SciencQuizEntry(discipline = listOf("Informatik"), person = listOf("Bjarne Stroustrup"), discovery = listOf("Entwicklung der Programmiersprache C++ durch Erweiterung von C um Klassen")),
        SciencQuizEntry(discipline = listOf("Informatik"), person = listOf("Linus Torvalds"), discovery = listOf("Initiator des Linux-Kernels und des Versionsverwaltungssystems Git")),
        SciencQuizEntry(discipline = listOf("Informatik"), person = listOf("Edsger W. Dijkstra"), discovery = listOf("Algorithmus zur Suche des kürzesten Weges in Graphen")),
        SciencQuizEntry(discipline = listOf("Informatik"), person = listOf("John McCarthy"), discovery = listOf("Erfindung der Programmiersprache Lisp und Pionier der künstlichen Intelligenz")),
        SciencQuizEntry(discipline = listOf("Informatik"), person = listOf("Ken Thompson"), discovery = listOf("Entwicklung des Betriebssystems Unix und der Programmiersprache B")),
        SciencQuizEntry(discipline = listOf("Informatik"), person = listOf("Donald Knuth"), discovery = listOf("Systematische Analyse von Algorithmen und Entwicklung eines Textsatzsystems")),

// --- GEOLOGIE ---
        SciencQuizEntry(discipline = listOf("Geologie"), person = listOf("Alfred Wegener"), discovery = listOf("Theorie der Kontinentaldrift und die Existenz des Superkontinents Pangäa")),
        SciencQuizEntry(discipline = listOf("Geologie"), person = listOf("Charles Lyell"), discovery = listOf("Prinzip des Aktualismus, nach dem geologische Prozesse der Vergangenheit noch heute wirken")),
        SciencQuizEntry(discipline = listOf("Geologie"), person = listOf("James Hutton"), discovery = listOf("Erkenntnis, dass die Erde weitaus älter ist als zuvor angenommen (Begründer der modernen Geologie)")),
        SciencQuizEntry(discipline = listOf("Geologie"), person = listOf("Inge Lehmann"), discovery = listOf("Entdeckung, dass der Erdkern aus einem festen inneren und einem flüssigen äußeren Teil besteht")),
        SciencQuizEntry(discipline = listOf("Geologie"), person = listOf("Marie Tharp"), discovery = listOf("Erstellung der ersten wissenschaftlichen Karte des Ozeanbodens und Entdeckung des Mittelatlantischen Rückens")),
        SciencQuizEntry(discipline = listOf("Geologie"), person = listOf("Harry Hess"), discovery = listOf("Theorie der Ozeanbodenspreizung als Mechanismus für die Kontinentaldrift")),
        SciencQuizEntry(discipline = listOf("Geologie"), person = listOf("Nicholas Steno"), discovery = listOf("Grundlegende Prinzipien der Stratigraphie, wie das Lagerungsgesetz von Gesteinsschichten")),
        SciencQuizEntry(discipline = listOf("Geologie"), person = listOf("Friedrich Mohs"), discovery = listOf("Entwicklung einer Skala zur Härtebestimmung von Mineralien")),
        SciencQuizEntry(discipline = listOf("Geologie"), person = listOf("Mary Anning"), discovery = listOf("Entdeckung zahlreicher bedeutender Fossilien von Meeresreptilien aus dem Jura")),
        SciencQuizEntry(discipline = listOf("Geologie"), person = listOf("Beno Gutenberg"), discovery = listOf("Bestimmung der Tiefe der Grenze zwischen Erdmantel und Erdkern")),
        SciencQuizEntry(discipline = listOf("Geologie"), person = listOf("Arthur Holmes"), discovery = listOf("Nutzung der Radioaktivität zur absoluten Altersbestimmung von Gesteinen")),
        SciencQuizEntry(discipline = listOf("Geologie"), person = listOf("Tuzo Wilson"), discovery = listOf("Konzept der Transformstörungen und Hotspots in der Plattentektonik")),
        SciencQuizEntry(discipline = listOf("Geologie"), person = listOf("William Smith"), discovery = listOf("Erste landesweite geologische Karte und Prinzip der Leitfossilien")),
        SciencQuizEntry(discipline = listOf("Geologie"), person = listOf("Georges Cuvier"), discovery = listOf("Begründung der Paläontologie durch vergleichende Anatomie und Katastrophismus")),

// --- MEDIZIN ---
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Hippokrates"), discovery = listOf("Begründung der Medizin als rationale Wissenschaft und Formulierung ethischer Grundregeln für Ärzte")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Andreas Vesalius"), discovery = listOf("Erstellung des ersten umfassenden und korrekten Atlas der menschlichen Anatomie")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Ignaz Semmelweis"), discovery = listOf("Nachweis, dass Hygiene und Händewaschen die Übertragung von Infektionskrankheiten drastisch reduzieren")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Joseph Lister"), discovery = listOf("Einführung chemischer Substanzen zur Keimabtötung während chirurgischer Eingriffe")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Florence Nightingale"), discovery = listOf("Revolution der Krankenpflege durch statistische Analysen und strikte Hygienestandards")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Sigmund Freud"), discovery = listOf("Begründung der Psychoanalyse und Erforschung des Unbewussten")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Frederick Banting"), discovery = listOf("Isolierung eines Hormons aus der Bauchspeicheldrüse zur lebensrettenden Behandlung von Zuckerkranken")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Jonas Salk"), discovery = listOf("Entwicklung eines injizierbaren Impfstoffs zum Schutz vor der spinalen Kinderlähmung")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Christiaan Barnard"), discovery = listOf("Durchführung der weltweit ersten erfolgreichen Verpflanzung eines menschlichen Herzens")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Luc Montagnier"), discovery = listOf("Identifizierung des Retrovirus, das für die Schwächung des menschlichen Immunsystems verantwortlich ist")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Barry Marshall"), discovery = listOf("Beweis durch Selbstversuch, dass Bakterien und nicht Stress die Hauptursache für Magengeschwüre sind")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Gertrude Elion"), discovery = listOf("Entwicklung rationaler Methoden für den Entwurf neuer Medikamente, unter anderem gegen Leukämie")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Virginia Apgar"), discovery = listOf("Entwicklung eines Schnelltests zur sofortigen Bewertung der Vitalfunktionen von Neugeborenen")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Christian Eijkman"), discovery = listOf("Nachweis, dass Mangelerscheinungen durch das Fehlen bestimmter Begleitstoffe in der Nahrung entstehen")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Gerhard Domagk"), discovery = listOf("Entdeckung der ersten antibiotisch wirksamen Sulfonamide zur Behandlung bakterieller Infektionen")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Selman Waksman"), discovery = listOf("Entdeckung eines Antibiotikums, das erstmals wirksam gegen die Tuberkulose eingesetzt werden konnte")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Thomas Starzl"), discovery = listOf("Pionierarbeit bei der ersten erfolgreichen Transplantation einer menschlichen Leber")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("Rosalyn Yalow"), discovery = listOf("Entwicklung einer extrem empfindlichen Methode zur Messung von Hormonkonzentrationen im Blut")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("James Lind"), discovery = listOf("Nachweis durch eine kontrollierte Studie, dass Zitrusfrüchte die Seefahrerkrankheit Skorbut heilen")),
        SciencQuizEntry(discipline = listOf("Medizin"), person = listOf("René Laënnec"), discovery = listOf("Erfindung eines Instruments zum Abhören der Herz- und Lungengeräusche im Körperinneren")),

// --- ASTRONOMIE ---
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Nicolaus Copernicus"), discovery = listOf("Modell eines Systems, in dem sich die Planeten um die Sonne statt um die Erde drehen")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Tycho Brahe"), discovery = listOf("Erstellung eines extrem präzisen Sternkatalogs vor der Erfindung des Fernrohrs")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("William Herschel"), discovery = listOf("Entdeckung des ersten Planeten der Neuzeit und Nachweis der Infrarotstrahlung")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Caroline Herschel"), discovery = listOf("Systematische Suche nach Kometen und Entdeckung von acht dieser Himmelskörper")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Henrietta Swan Leavitt"), discovery = listOf("Methode zur Distanzmessung im Weltall durch die Beobachtung veränderlicher Sterne")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Jocelyn Bell Burnell"), discovery = listOf("Nachweis von Radiosignalen, die von schnell rotierenden Neutronensternen ausgehen")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Clyde Tombaugh"), discovery = listOf("Auffindung eines Himmelskörpers am Rande des Sonnensystems, der lange als neunter Planet galt")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Annie Jump Cannon"), discovery = listOf("Katalogisierung von Hunderttausenden Sternen basierend auf ihren Spektraltypen")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Edmond Halley"), discovery = listOf("Berechnung der Umlaufbahn eines Kometen und Vorhersage seiner periodischen Wiederkehr")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Fritz Zwicky"), discovery = listOf("Theoretische Vorhersage von Neutronensternen und Hinweis auf unsichtbare Materie in Galaxienhaufen")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Arno Penzias & Robert Wilson"), discovery = listOf("Nachweis eines schwachen Mikrowellenrauschens aus allen Richtungen des Weltalls")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Giovanni Cassini"), discovery = listOf("Entdeckung der Teilung in den Ringen des Planeten Saturn")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Hipparchos"), discovery = listOf("Erstellung des ersten Sternkatalogs der westlichen Welt und Entdeckung der Präzession")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Cecilia Payne-Gaposchkin"), discovery = listOf("Erkenntnis, dass Sterne hauptsächlich aus Wasserstoff und Helium bestehen")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Karl Jansky"), discovery = listOf("Begründung der Radioastronomie durch den Nachweis von Radiowellen aus dem Zentrum der Milchstraße")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Fred Hoyle"), discovery = listOf("Theorie der Sternentstehung und Prägung des Begriffs für den Urknall")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Ejnar Hertzsprung & Henry Norris Russell"), discovery = listOf("Diagramm zur Klassifizierung von Sternen nach Leuchtkraft und Farbe")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Eugene Shoemaker"), discovery = listOf("Mitentdeckung eines Kometen, der auf Jupiter einschlug, und Begründung der Astrogeologie")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Aristarchos von Samos"), discovery = listOf("Erstmaliges heliozentrisches Modell der Antike und Schätzung der Entfernung zur Sonne")),
        SciencQuizEntry(discipline = listOf("Astronomie"), person = listOf("Arthur Eddington"), discovery = listOf("Experimenteller Beweis der Lichtablenkung durch Gravitation während einer Sonnenfinsternis")),
    )
}
